chore: add moove testimonial
open-metadata/openmetadata-site pull request #104
Opened 2023-08-09 19:45 UTC by Sachin-chaurasiya

<img width="1431" alt="image" src="https://github.com/open-metadata/openmetadata-site/assets/59080942/c2771588-9675-40bb-8f66-9a2194d775fb">

<img width="1439" alt="image" src="https://github.com/open-metadata/openmetadata-site/assets/59080942/c0b0f7fa-5015-494c-ba3b-add791e58b3b">

2023-08-09 19:55 UTC, harshach approved these changes

2023-08-09 23:47 UTC, ShilpaVernekar commented on js/testimonials.json
> +    "description": "OpenMetadata has been an invaluable tool for our organization. With its user-friendly interface and powerful features, we have streamlined our data management and governance proce
"OpenMetadata has been an invaluable tool for our organization. With its user-friendly interface and powerful features, we have streamlined our data management and governance processes. **OpenMetadata's** collaborative features have fostered better communication and collaboration among our teams, ensuring everyone is on the same page regarding data assets. Furthermore, the extensive integration options and APIs have allowed us to seamlessly integrate OpenMetadata into our existing data infrastructure, making the implementation process smooth and efficient. The **platform's** strong data lineage and discovery capabilities have been a game-changer, helping us gain deeper insights into our data and ensuring data compliance. Overall, OpenMetadata has exceeded our expectations and has become an integral part of our data governance strategy. We highly recommend it to any organization seeking to enhance their data management, governance, and data-driven decision-making processes."

2023-08-09 23:47 UTC, ShilpaVernekar requested changes
Hi @Sachin-chaurasiya - the text doesn't look right - marked two places that need "'s"

2023-08-10 05:30 UTC, Sachin-chaurasiya commented
> Hi @Sachin-chaurasiya - the text doesn't look right - marked two places that need "'s"

Hello @ShilpaVernekar , Done.

2023-08-10 05:59 UTC, ShilpaVernekar approved these changes
Looks good

2023-08-10 06:00 UTC, merged